<Project Sdk="Microsoft.NET.Sdk">
  <!-- Webアプリとは別の実行ファイル(バッチ)。普通のコンソールアプリの SDK -->
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net5.0</TargetFramework>
    <LangVersion>9.0</LangVersion>
    <Nullable>enable</Nullable>
    <RollForward>LatestMajor</RollForward>
    <CheckEolTargetFramework>false</CheckEolTargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <ProjectReference Include="..\Reports\Reports.csproj" />
  </ItemGroup>
</Project>
